In [233]:
import pandas as pd
import numpy as np

## read the JSON file that you saved in ex02

In [234]:
df = pd.read_json('../ex02/auto.json')

In [235]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  725 non-null    object
 1   Refund     725 non-null    int64
 2   Fines      725 non-null    float64
 3   Make       725 non-null    object
 4   Model      716 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 28.4+ KB

In [236]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [237]:
df

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

## enrich the dataframe using a sample from that dataframe

In [238]:
sample_df = df.sample(200, random_state=21)

In [239]:
concat_rows = pd.concat([df, sample_df])

In [240]:
concat_rows.index = range(len(concat_rows))

In [241]:
concat_rows

        CarNumber  Refund   Fines        Make   Model
0    Y163O8161RUS       2 3200.00        Ford   Focus
1     E432XX77RUS       1 6500.00      Toyota   Camry
2     7184TT36RUS       1 2100.00        Ford   Focus
3    X582HE161RUS       2 2000.00        Ford   Focus
4    92918M178RUS       1 5700.00        Ford   Focus
..            ...     ...     ...         ...     ...
920  8182XX154RUS       1  200.00        Ford   Focus
921   X796TH96RUS       1  500.00        Ford   Focus
922  T011MY163RUS       2 4000.00        Ford   Focus
923   T341CC96RUS       2 1000.00  Volkswagen  Passat
924   T119CT96RUS       1 2000.00        Ford   Focus

[925 rows x 5 columns]

## enrich the dataframe concat_rows by a new column with the data generated

In [242]:
len(concat_rows)

925

In [243]:
np.random.seed(21)
Year = np.random.randint(1980, 2019, len(concat_rows))
Year = pd.Series(Year, name='Year')

In [244]:
Year

0      1989
1      1995
2      1984
3      2015
4      2014
       ...
920    1996
921    2002
922    1996
923    2012
924    1984
Name: Year, Length: 925, dtype: int64

In [245]:
fines = pd.concat([concat_rows, Year], axis=1)

In [246]:
fines

        CarNumber  Refund   Fines        Make   Model  Year
0    Y163O8161RUS       2 3200.00        Ford   Focus  1989
1     E432XX77RUS       1 6500.00      Toyota   Camry  1995
2     7184TT36RUS       1 2100.00        Ford   Focus  1984
3    X582HE161RUS       2 2000.00        Ford   Focus  2015
4    92918M178RUS       1 5700.00        Ford   Focus  2014
..            ...     ...     ...         ...     ...   ...
920  8182XX154RUS       1  200.00        Ford   Focus  1996
921   X796TH96RUS       1  500.00        Ford   Focus  2002
922  T011MY163RUS       2 4000.00        Ford   Focus  1996
923   T341CC96RUS       2 1000.00  Volkswagen  Passat  2012
924   T119CT96RUS       1 2000.00        Ford   Focus  1984

[925 rows x 6 columns]

## enrich the dataframe with the data from another dataframe

#### create a new dataframe with the car numbers and their owners

In [247]:
surname = pd.read_json('../../datasets/surname.json')

In [248]:
surname.columns = surname.iloc[0]

In [249]:
surname = surname[1:]

In [250]:
surname = surname.reset_index(drop=True)

In [251]:
surname

0       NAME    COUNT RANK
0      ADAMS   427865   42
1      ALLEN   482607   33
2    ALVAREZ   233983   92
3   ANDERSON   784404   15
4     BAILEY   277845   72
..       ...      ...  ...
95  WILLIAMS  1625252    3
96    WILSON   801882   14
97      WOOD   250715   84
98    WRIGHT   458980   35
99     YOUNG   484447   32

[100 rows x 3 columns]

In [252]:
unique_car_nums = concat_rows['CarNumber'].unique()

In [253]:
len(unique_car_nums)

531

In [254]:
np.random_state = 21
surnames = pd.Series(np.random.choice(surname['NAME'], size=len(unique_car_nums)))
surnames

0        TURNER
1      MARTINEZ
2          HALL
3          REED
4       SANCHEZ
         ...
526       YOUNG
527       BROWN
528         COX
529        GRAY
530     ROBERTS
Length: 531, dtype: object

In [255]:
owners = pd.DataFrame()

In [256]:
owners['CarNumber'] = unique_car_nums
owners['SURNAME'] = surnames
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
526  O136HO197RUS     YOUNG
527  O22097197RUS     BROWN
528  M0309X197RUS       COX
529  O673E8197RUS      GRAY
530  8610T8154RUS   ROBERTS

[531 rows x 2 columns]

#### append 5 more observations to the fines dataframe (come up with your own ideas of CarNumber, etc.)

In [257]:
fines

        CarNumber  Refund   Fines        Make   Model  Year
0    Y163O8161RUS       2 3200.00        Ford   Focus  1989
1     E432XX77RUS       1 6500.00      Toyota   Camry  1995
2     7184TT36RUS       1 2100.00        Ford   Focus  1984
3    X582HE161RUS       2 2000.00        Ford   Focus  2015
4    92918M178RUS       1 5700.00        Ford   Focus  2014
..            ...     ...     ...         ...     ...   ...
920  8182XX154RUS       1  200.00        Ford   Focus  1996
921   X796TH96RUS       1  500.00        Ford   Focus  2002
922  T011MY163RUS       2 4000.00        Ford   Focus  1996
923   T341CC96RUS       2 1000.00  Volkswagen  Passat  2012
924   T119CT96RUS       1 2000.00        Ford   Focus  1984

[925 rows x 6 columns]

In [258]:
fines.loc[len(fines)] = ['FK7362JG322RUS', 1, 7200.00, 'Hyundai', 'Solaris', 2016]
fines.loc[len(fines)] = ['US738G728RUS', 1, 1800.00, 'Porsche', 'Cayenne', 2012]
fines.loc[len(fines)] = ['AA837YH192RUS', 1, 6500.00, 'Hyundai', 'Accent', 2010]
fines.loc[len(fines)] = ['GJ123H3P128RUS', 1, 7400.00, 'Lada', 'Granta', 2014]
fines.loc[len(fines)] = ['KP341H177RUS', 1, 9200.00, 'Ford', 'Focus', 2015]

#### delete the dataframe last 20 observations from the owners and add 3 new observations (they are not the same as those you add to the fines dataframe)

In [259]:
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
526  O136HO197RUS     YOUNG
527  O22097197RUS     BROWN
528  M0309X197RUS       COX
529  O673E8197RUS      GRAY
530  8610T8154RUS   ROBERTS

[531 rows x 2 columns]

In [260]:
owners = owners[:len(owners) - 20]

In [261]:
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
506  T914CT197RUS      DIAZ
507  E41977152RUS     CLARK
508  9464EX178RUS     BAKER
509  O50197197RUS   ALVAREZ
510  7608EE777RUS      RUIZ

[511 rows x 2 columns]

In [262]:
# owners.loc[len(owners)] = ['SJ0273Y61RUS', 'RODGERS']
# owners.loc[len(owners)] = ['AP321E161RUS', 'JHONSONS']
# owners.loc[len(owners)] = ['CS527Y161RUS', 'COOPERS']
new_rows = pd.DataFrame({
    'CarNumber': ['SJ0273Y61RUS', 'AP321E161RUS', 'CS527Y161RUS'],
    'SURNAME': ['RODGERS', 'JHONSONS', 'COOPERS']
})

owners = pd.concat([owners, new_rows], ignore_index=True)

In [263]:
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
509  O50197197RUS   ALVAREZ
510  7608EE777RUS      RUIZ
511  SJ0273Y61RUS   RODGERS
512  AP321E161RUS  JHONSONS
513  CS527Y161RUS   COOPERS

[514 rows x 2 columns]

#### join both dataframes

In [264]:
fines.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

In [265]:
owners.head()

      CarNumber   SURNAME
0  Y163O8161RUS    TURNER
1   E432XX77RUS  MARTINEZ
2   7184TT36RUS      HALL
3  X582HE161RUS      REED
4  92918M178RUS   SANCHEZ

In [266]:
## the new dataframe should have only the car numbers that exist in both dataframes
pd.merge(fines, owners, on='CarNumber', how='inner')

        CarNumber  Refund    Fines    Make    Model  Year   SURNAME
0    Y163O8161RUS       2  3200.00    Ford    Focus  1989    TURNER
1    Y163O8161RUS       2  1600.00    Ford    Focus  1999    TURNER
2     E432XX77RUS       1  6500.00  Toyota    Camry  1995  MARTINEZ
3     E432XX77RUS       2 13000.00  Toyota    Camry  1992  MARTINEZ
4     7184TT36RUS       1  2100.00    Ford    Focus  1984      HALL
..            ...     ...      ...     ...      ...   ...       ...
894  E41977152RUS       2  2400.00    Ford    Focus  2001     CLARK
895  9464EX178RUS       2  2100.00    Ford    Focus  1993     BAKER
896  O50197197RUS       2  7800.00    Ford    Focus  1986   ALVAREZ
897  7608EE777RUS       1  4000.00   Skoda  Octavia  2013      RUIZ
898  7608EE777RUS       1  4000.00   Skoda  Octavia  1987      RUIZ

[899 rows x 7 columns]

In [267]:
## the new dataframe should have all the car numbers that exist in both dataframes
pd.merge(fines, owners, on='CarNumber', how='outer')

          CarNumber  Refund    Fines    Make   Model    Year   SURNAME
0      Y163O8161RUS    2.00  3200.00    Ford   Focus 1989.00    TURNER
1      Y163O8161RUS    2.00  1600.00    Ford   Focus 1999.00    TURNER
2       E432XX77RUS    1.00  6500.00  Toyota   Camry 1995.00  MARTINEZ
3       E432XX77RUS    2.00 13000.00  Toyota   Camry 1992.00  MARTINEZ
4       7184TT36RUS    1.00  2100.00    Ford   Focus 1984.00      HALL
..              ...     ...      ...     ...     ...     ...       ...
928  GJ123H3P128RUS    1.00  7400.00    Lada  Granta 2014.00       NaN
929    KP341H177RUS    1.00  9200.00    Ford   Focus 2015.00       NaN
930    SJ0273Y61RUS     NaN      NaN     NaN     NaN     NaN   RODGERS
931    AP321E161RUS     NaN      NaN     NaN     NaN     NaN  JHONSONS
932    CS527Y161RUS     NaN      NaN     NaN     NaN     NaN   COOPERS

[933 rows x 7 columns]

In [268]:
## the new dataframe should have only the car numbers from the fines dataframe
pd.merge(fines, owners, on='CarNumber', how='left')

          CarNumber  Refund   Fines     Make    Model  Year   SURNAME
0      Y163O8161RUS       2 3200.00     Ford    Focus  1989    TURNER
1       E432XX77RUS       1 6500.00   Toyota    Camry  1995  MARTINEZ
2       7184TT36RUS       1 2100.00     Ford    Focus  1984      HALL
3      X582HE161RUS       2 2000.00     Ford    Focus  2015      REED
4      92918M178RUS       1 5700.00     Ford    Focus  2014   SANCHEZ
..              ...     ...     ...      ...      ...   ...       ...
925  FK7362JG322RUS       1 7200.00  Hyundai  Solaris  2016       NaN
926    US738G728RUS       1 1800.00  Porsche  Cayenne  2012       NaN
927   AA837YH192RUS       1 6500.00  Hyundai   Accent  2010       NaN
928  GJ123H3P128RUS       1 7400.00     Lada   Granta  2014       NaN
929    KP341H177RUS       1 9200.00     Ford    Focus  2015       NaN

[930 rows x 7 columns]

In [269]:
## the new dataframe should have only the car numbers from the owners dataframe
pd.merge(fines, owners, on='CarNumber', how='right')

        CarNumber  Refund    Fines    Make    Model    Year   SURNAME
0    Y163O8161RUS    2.00  3200.00    Ford    Focus 1989.00    TURNER
1    Y163O8161RUS    2.00  1600.00    Ford    Focus 1999.00    TURNER
2     E432XX77RUS    1.00  6500.00  Toyota    Camry 1995.00  MARTINEZ
3     E432XX77RUS    2.00 13000.00  Toyota    Camry 1992.00  MARTINEZ
4     7184TT36RUS    1.00  2100.00    Ford    Focus 1984.00      HALL
..            ...     ...      ...     ...      ...     ...       ...
897  7608EE777RUS    1.00  4000.00   Skoda  Octavia 2013.00      RUIZ
898  7608EE777RUS    1.00  4000.00   Skoda  Octavia 1987.00      RUIZ
899  SJ0273Y61RUS     NaN      NaN     NaN      NaN     NaN   RODGERS
900  AP321E161RUS     NaN      NaN     NaN      NaN     NaN  JHONSONS
901  CS527Y161RUS     NaN      NaN     NaN      NaN     NaN   COOPERS

[902 rows x 7 columns]

## create a pivot table from the fines dataframe, it should look like this (the values are the sums of the fines), but with all the years (the values may be different for you)

In [270]:
pd.pivot_table(fines, values='Fines', index=['Make', 'Model'], columns='Year', aggfunc='sum')

Year                   1980      1981      1982      1983      1984      1985  \
Make       Model
Ford       Focus   89194.59 266783.76 107283.76 147289.17 106000.00 307494.59
           Mondeo       NaN       NaN  46200.00       NaN       NaN       NaN
Hyundai    Accent       NaN       NaN       NaN       NaN       NaN       NaN
           Solaris      NaN       NaN       NaN       NaN       NaN       NaN
Lada       Granta       NaN       NaN       NaN       NaN       NaN       NaN
Porsche    Cayenne      NaN       NaN       NaN       NaN       NaN       NaN
Skoda      Octavia 13794.59   1900.00   8894.59       NaN   1300.00 153594.59
Toyota     Camry   12000.00       NaN   1000.00   8594.59   1000.00       NaN
           Corolla      NaN   6800.00       NaN  12800.00       NaN   4400.00
Volkswagen Golf    20800.00   8594.59   5000.00    200.00       NaN 168000.00
           Jetta        NaN   1000.00       NaN       NaN       NaN   9000.00
           Passat    900.00  12500.00       NaN   1100.00   8594.59       NaN
           Touareg      NaN       NaN       NaN       NaN       NaN       NaN

Year                   1986     1987     1988      1989  ...      2009  \
Make       Model                                         ...
Ford       Focus   69700.00 98189.17 69667.52 200889.17  ... 159894.59
           Mondeo       NaN      NaN      NaN       NaN  ...       NaN
Hyundai    Accent       NaN      NaN      NaN       NaN  ...       NaN
           Solaris      NaN      NaN      NaN       NaN  ...       NaN
Lada       Granta       NaN      NaN      NaN       NaN  ...       NaN
Porsche    Cayenne      NaN      NaN      NaN       NaN  ...       NaN
Skoda      Octavia      NaN  6000.00  5100.00   8594.59  ...       NaN
Toyota     Camry   19800.00      NaN      NaN    800.00  ...       NaN
           Corolla      NaN 54300.00      NaN   7800.00  ...   8594.59
Volkswagen Golf         NaN   300.00      NaN    300.00  ...       NaN
           Jetta        NaN      NaN 46000.00   4000.00  ...       NaN
           Passat  16000.00  2000.00  8594.59       NaN  ...   3200.00
           Touareg      NaN      NaN      NaN       NaN  ...   5800.00

Year                   2010      2011      2012      2013     2014      2015  \
Make       Model
Ford       Focus   96000.00 117194.59 152989.17 297378.35 90378.35 181900.00
           Mondeo       NaN       NaN       NaN  41100.00      NaN       NaN
Hyundai    Accent   6500.00       NaN       NaN       NaN      NaN       NaN
           Solaris      NaN       NaN       NaN       NaN      NaN       NaN
Lada       Granta       NaN       NaN       NaN       NaN  7400.00       NaN
Porsche    Cayenne      NaN       NaN   1800.00       NaN      NaN       NaN
Skoda      Octavia  3000.00   3000.00   1700.00  11800.00 18900.00  16394.59
Toyota     Camry   22400.00       NaN   7500.00       NaN      NaN       NaN
           Corolla  6000.00   3400.00       NaN       NaN      NaN  30300.00
Volkswagen Golf         NaN       NaN       NaN       NaN 13900.00   4600.00
           Jetta        NaN       NaN       NaN       NaN      NaN       NaN
           Passat   9500.00       NaN   1000.00   1600.00 15000.00       NaN
           Touareg      NaN       NaN       NaN       NaN      NaN       NaN

Year                    2016      2017      2018
Make       Model
Ford       Focus   110789.17 114089.17 107800.00
           Mondeo        NaN   8600.00       NaN
Hyundai    Accent        NaN       NaN       NaN
           Solaris   7200.00       NaN       NaN
Lada       Granta        NaN       NaN       NaN
Porsche    Cayenne       NaN       NaN       NaN
Skoda      Octavia  35700.00   2400.00 153200.00
Toyota     Camry      800.00       NaN       NaN
           Corolla       NaN   6900.00       NaN
Volkswagen Golf          NaN       NaN   1000.00
           Jetta         NaN       NaN       NaN
           Passat        NaN       NaN       NaN
           Touareg       NaN       NaN       NaN

[13 rows x 39 columns]

## save both the fines and owners dataframes to CSV files without an index

In [271]:
fines.to_csv('fines.csv', index=None)
owners.to_csv('owners.csv', index=None)