In [1]:
#  Install
# sudo apt update
# sudo apt install python3-pandas

In [2]:
import pandas as pd

## read_csv

In [5]:
data = pd.read_csv('./feed-views.log', sep='\t', skiprows=[2, 3], skipfooter=2, names=['datetime', 'user'], engine='python')

In [39]:
data = data.set_index('datetime')

In [6]:
data

                        datetime       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:35:52.735016      artem
3     2020-04-17 12:36:21.401412     oksana
4     2020-04-17 12:36:22.023355     oksana
...                          ...        ...
1067  2020-05-21 16:36:40.915488  ekaterina
1068  2020-05-21 17:49:36.429237      maxim
1069  2020-05-21 18:45:20.441142  valentina
1070  2020-05-21 23:03:06.457819      maxim
1071  2020-05-21 23:23:49.995349      pavel

[1072 rows x 2 columns]

## rename datetime to date_time

In [7]:
data = data.reset_index()

In [8]:
data = data.rename(columns={'datetime': 'date_time'})

In [9]:
data = data.set_index('date_time')

In [10]:
data

                            index       user
date_time
2020-04-17 12:01:08.463179      0      artem
2020-04-17 12:01:23.743946      1      artem
2020-04-17 12:35:52.735016      2      artem
2020-04-17 12:36:21.401412      3     oksana
2020-04-17 12:36:22.023355      4     oksana
...                           ...        ...
2020-05-21 16:36:40.915488   1067  ekaterina
2020-05-21 17:49:36.429237   1068      maxim
2020-05-21 18:45:20.441142   1069  valentina
2020-05-21 23:03:06.457819   1070      maxim
2020-05-21 23:23:49.995349   1071      pavel

[1072 rows x 2 columns]

## to_csv

In [48]:
data.to_csv('feed-views-semicolon.log', sep=';')