In [68]:
import pandas as pd

## read the fines.csv that you saved in the previous exercise

In [69]:
df = pd.read_csv('../ex04/fines.csv')

In [70]:
df

          CarNumber  Refund   Fines     Make    Model  Year
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995
2       7184TT36RUS       1  2100.0     Ford    Focus  1984
3      X582HE161RUS       2  2000.0     Ford    Focus  2015
4      92918M178RUS       1  5700.0     Ford    Focus  2014
..              ...     ...     ...      ...      ...   ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014
929    KP341H177RUS       1  9200.0     Ford    Focus  2015

[930 rows x 6 columns]

## iterations: in all the following subtasks, you need to calculate fines/refund*year for each row and create a new column with the calculated data and measure the time using the magic command %%timeit in the cell

In [71]:
%%timeit -n1 -r1
## loop
list_with_values = list()
for i in range(len(df)):
    result = df.loc[i, 'Fines'] / df.loc[i, 'Refund'] * df.loc[i, 'Year']
    list_with_values.append(result)
df['New Column'] = list_with_values
print(df)

          CarNumber  Refund   Fines     Make    Model  Year  New Column
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989   3182400.0
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995  12967500.0
2       7184TT36RUS       1  2100.0     Ford    Focus  1984   4166400.0
3      X582HE161RUS       2  2000.0     Ford    Focus  2015   2015000.0
4      92918M178RUS       1  5700.0     Ford    Focus  2014  11479800.0
..              ...     ...     ...      ...      ...   ...         ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016  14515200.0
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012   3621600.0
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010  13065000.0
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014  14903600.0
929    KP341H177RUS       1  9200.0     Ford    Focus  2015  18538000.0

[930 rows x 7 columns]
87.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [72]:
%%timeit -n1 -r1
## iterrows()
list_with_values = list()
for index, row in df.iterrows():
    result = row['Fines'] / row['Refund'] * row['Year']
    list_with_values.append(result)
df['New Column'] = list_with_values
print(df)

          CarNumber  Refund   Fines     Make    Model  Year  New Column
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989   3182400.0
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995  12967500.0
2       7184TT36RUS       1  2100.0     Ford    Focus  1984   4166400.0
3      X582HE161RUS       2  2000.0     Ford    Focus  2015   2015000.0
4      92918M178RUS       1  5700.0     Ford    Focus  2014  11479800.0
..              ...     ...     ...      ...      ...   ...         ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016  14515200.0
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012   3621600.0
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010  13065000.0
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014  14903600.0
929    KP341H177RUS       1  9200.0     Ford    Focus  2015  18538000.0

[930 rows x 7 columns]
145 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [73]:
%%timeit -n1 -r1
## apply() and lambda function
df['New Column'] = df.apply(lambda x: x['Fines'] / x['Refund'] * x['Year'], axis=1)
print(df)

          CarNumber  Refund   Fines     Make    Model  Year  New Column
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989   3182400.0
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995  12967500.0
2       7184TT36RUS       1  2100.0     Ford    Focus  1984   4166400.0
3      X582HE161RUS       2  2000.0     Ford    Focus  2015   2015000.0
4      92918M178RUS       1  5700.0     Ford    Focus  2014  11479800.0
..              ...     ...     ...      ...      ...   ...         ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016  14515200.0
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012   3621600.0
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010  13065000.0
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014  14903600.0
929    KP341H177RUS       1  9200.0     Ford    Focus  2015  18538000.0

[930 rows x 7 columns]
50.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [74]:
%%timeit -n1 -r1
## using Series objects from the dataframe
df['New Column'] = df['Fines'] / df['Refund'] * df['Year']
print(df)

          CarNumber  Refund   Fines     Make    Model  Year  New Column
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989   3182400.0
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995  12967500.0
2       7184TT36RUS       1  2100.0     Ford    Focus  1984   4166400.0
3      X582HE161RUS       2  2000.0     Ford    Focus  2015   2015000.0
4      92918M178RUS       1  5700.0     Ford    Focus  2014  11479800.0
..              ...     ...     ...      ...      ...   ...         ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016  14515200.0
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012   3621600.0
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010  13065000.0
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014  14903600.0
929    KP341H177RUS       1  9200.0     Ford    Focus  2015  18538000.0

[930 rows x 7 columns]
32.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [75]:
%%timeit -n1 -r1
## method .values()
df['New Column'] = df['Fines'].values / df['Refund'].values * df['Year'].values
print(df)

          CarNumber  Refund   Fines     Make    Model  Year  New Column
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989   3182400.0
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995  12967500.0
2       7184TT36RUS       1  2100.0     Ford    Focus  1984   4166400.0
3      X582HE161RUS       2  2000.0     Ford    Focus  2015   2015000.0
4      92918M178RUS       1  5700.0     Ford    Focus  2014  11479800.0
..              ...     ...     ...      ...      ...   ...         ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016  14515200.0
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012   3621600.0
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010  13065000.0
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014  14903600.0
929    KP341H177RUS       1  9200.0     Ford    Focus  2015  18538000.0

[930 rows x 7 columns]
21.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

## indexing: measure the time using the magic command %%timeit in the cell

In [76]:
%%timeit -n1 -r1 
car_number = 'O136HO197RUS'
print(df[df['CarNumber'] == car_number])

        CarNumber  Refund   Fines    Make    Model  Year  New Column
715  O136HO197RUS       2  7800.0  Toyota  Corolla  1989   7757100.0
902  O136HO197RUS       2  7800.0  Toyota  Corolla  1997   7788300.0
34.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [77]:
df = df.set_index('CarNumber')

In [79]:
%%timeit -n1 -r1
car_number = 'O136HO197RUS'
print(df.loc[car_number])

              Refund   Fines    Make    Model  Year  New Column
CarNumber
O136HO197RUS       2  7800.0  Toyota  Corolla  1989   7757100.0
O136HO197RUS       2  7800.0  Toyota  Corolla  1997   7788300.0
19.9 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

## downcasting

In [80]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to KP341H177RUS
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    int64
 1   Fines       930 non-null    float64
 2   Make        930 non-null    object
 3   Model       919 non-null    object
 4   Year        930 non-null    int64
 5   New Column  930 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 214.3 KB

In [81]:
df = pd.read_csv('../ex04/fines.csv')

In [82]:
optimized = df.copy()

In [83]:
optimized

          CarNumber  Refund   Fines     Make    Model  Year
0      Y163O8161RUS       2  3200.0     Ford    Focus  1989
1       E432XX77RUS       1  6500.0   Toyota    Camry  1995
2       7184TT36RUS       1  2100.0     Ford    Focus  1984
3      X582HE161RUS       2  2000.0     Ford    Focus  2015
4      92918M178RUS       1  5700.0     Ford    Focus  2014
..              ...     ...     ...      ...      ...   ...
925  FK7362JG322RUS       1  7200.0  Hyundai  Solaris  2016
926    US738G728RUS       1  1800.0  Porsche  Cayenne  2012
927   AA837YH192RUS       1  6500.0  Hyundai   Accent  2010
928  GJ123H3P128RUS       1  7400.0     Lada   Granta  2014
929    KP341H177RUS       1  9200.0     Ford    Focus  2015

[930 rows x 6 columns]