In [167]:
import pandas as pd

## load the JSON file that you created in the previous exercise into a dataframe

In [168]:
df = pd.read_json('../ex02/auto.json')

In [169]:
df = df.set_index('CarNumber')

In [170]:
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

## make the following selects

In [171]:
# display the rows only where the fines are more than 2,100
df[df['Fines'] > 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

In [172]:
# display the rows only where the fines are more than 2,100 and the refund equals 2
df[(df['Fines'] > 2100) & (df['Refund'] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [173]:
# display the rows only where the models are from the list: [’Focus’, ’Corolla’]
df[df['Model'].isin(['Focus', 'Corolla'])]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [174]:
# display the rows only where the car number is from the list: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]
df_without_index = df.reset_index()
df_without_index[df_without_index['CarNumber'].isin(['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'])]

        CarNumber  Refund          Fines  Make  Model
28   92928M178RUS       1    8594.586466  Ford  Focus
35   H115YO163RUS       1    2200.000000  Ford  Focus
71   7788KT197RUS       2   12000.000000  Ford  Focus
98   X758HY197RUS       2   24200.000000  Ford  Focus
158  X758HY197RUS       2   72600.000000  Ford  Focus
183  Y7689C197RUS       1   27000.000000  Ford  Focus
191  92928M178RUS       1     600.000000  Ford  Focus
215  H115YO163RUS       1    8594.586466  Ford  Focus
272  H115YO163RUS       2    1100.000000  Ford  Focus
283  7788KT197RUS       2    8594.586466  Ford  Focus
376  7788KT197RUS       1   20000.000000  Ford  Focus
401  X758HY197RUS       2  145200.000000  Ford  Focus
465  92928M178RUS       1    1200.000000  Ford  Focus
531  Y7689C197RUS       2    9000.000000  Ford  Focus
554  Y7689C197RUS       2   45000.000000  Ford  Focus
555  7788KT197RUS       2    4000.000000  Ford  Focus
665  Y7689C197RUS       1   36000.000000  Ford  Focus
674  92928M178RUS       2    3000.000000  Ford  Focus

## make the aggregations with the make and the model

In [175]:
# display the median fines grouped by the make
grouped = df.groupby('Make')
grouped['Fines'].mean()

Make
Audi           4200.000000
BMW            6031.528822
Ford           8270.665045
Skoda         10586.710526
Toyota         9478.934100
Volkswagen     9929.970462
Volvo          8500.000000
Name: Fines, dtype: float64

In [176]:
# display the median fines grouped by the make and the model
grouped = df.groupby(['Make', 'Model'])
grouped['Fines'].mean()

Make        Model
Ford        Focus       8184.445897
            Mondeo     16533.333333
Skoda       Octavia    10586.710526
Toyota      Camry       8236.823308
            Corolla    10583.032581
Volkswagen  Golf       15744.729323
            Jetta      10350.000000
            Passat      6363.144224
            Touareg     4498.917293
Name: Fines, dtype: float64

In [177]:
# display the number of fines grouped by the make and the model in order to understand if we can trust the median values
grouped = df.groupby(['Make', 'Model'])
grouped['Fines'].count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [178]:
# display the minimum and the maximum fines grouped by the make and the model in order to better understand the variance
grouped = df.groupby(['Make', 'Model'])
print(grouped['Fines'].min())
print(grouped['Fines'].max())

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64
Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

In [179]:
# display the standard deviation of the fines grouped by the make and the model in order to better understand the variance
grouped = df.groupby(['Make', 'Model'])
grouped['Fines'].std()

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## make the aggregations with the car number

In [180]:
df = df.reset_index()

In [181]:
# display the car numbers grouped by the number of the fines in descending order, we want to find those who most often violated the law
df.groupby('CarNumber')['Fines'].size().sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Name: Fines, Length: 531, dtype: int64

In [182]:
# select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
init_df = pd.read_json('../ex02/auto.json')
init_df[init_df['CarNumber'] == 'Y7689C197RUS']

        CarNumber  Refund    Fines  Make  Model
183  Y7689C197RUS       1  27000.0  Ford  Focus
531  Y7689C197RUS       2   9000.0  Ford  Focus
554  Y7689C197RUS       2  45000.0  Ford  Focus
665  Y7689C197RUS       1  36000.0  Ford  Focus

In [183]:
# display the car numbers grouped by the sum of the fines in descending order, we want to find those who paid the most
df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [184]:
# select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
init_df[init_df['CarNumber'] == 'X758HY197RUS']

        CarNumber  Refund     Fines  Make  Model
98   X758HY197RUS       2   24200.0  Ford  Focus
158  X758HY197RUS       2   72600.0  Ford  Focus
401  X758HY197RUS       2  145200.0  Ford  Focus

In [185]:
# display a table that answers the question: are there any car numbers that were connected to different models?
grouped = df.groupby('CarNumber')['Model'].nunique()
grouped[grouped > 1]

Series([], Name: Model, dtype: int64)