In [232]:
import pandas as pd

## download and read the CSV file and make ID the index column

In [233]:
df = pd.read_csv('auto.csv', index_col='ID')

In [234]:
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

## count the number of observations using the method count()

In [235]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

## drop the duplicates, taking into account only the following columns: CarNumber, Make_n_model, Fines

In [236]:
df = df.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last')

In [237]:
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## work with missing values

In [238]:
df.isna().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [239]:
df.shape

(725, 5)

In [240]:
df = df.dropna(thresh=224, axis=1)

In [241]:
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [242]:
# df['Refund'] = df['Refund'].fillna(method='ffill')
df['Refund'] = df['Refund'].ffill()

In [243]:
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [244]:
fines_mean = df['Fines'][df['Fines'] != 0].mean()

In [245]:
df['Fines'] = df['Fines'].fillna(fines_mean)

In [246]:
df.isna().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

## split and parse the make and model

In [247]:
df['Make'] = df['Make_n_model'].apply(lambda x: x.split()[0])

In [248]:
df['Model'] = df['Make_n_model'].apply(lambda x: x.split()[1] if len(x.split()) > 1 else None)

In [249]:
df = df.drop('Make_n_model', axis=1)

In [250]:
df.isna().sum()

CarNumber    0
Refund       0
Fines        0
Make         0
Model        9
dtype: int64

In [251]:
df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [253]:
df.to_json('auto.json', orient='records')